// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller.js"
application.register("alert", AlertController)

import ContactoController from "./contacto_controller.js"
application.register("contacto", ContactoController)

import DropdownBarsController from "./dropdown_bars_controller.js"
application.register("dropdown-bars", DropdownBarsController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import IntersectionObserverController from "./intersection_observer_controller.js"
application.register("intersection-observer", IntersectionObserverController)

import ResetFormController from "./reset_form_controller.js"
application.register("reset-form", ResetFormController)

import UserIndexController from "./user_index_controller.js"
application.register("user-index", UserIndexController)

import UserSearchbarController from "./user_searchbar_controller.js"
application.register("user-searchbar", UserSearchbarController)
